version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*bufio.Reader).UnreadByte
