namespace Pakt.Serialization;

/// <summary>
/// Provides metadata and serialization delegates for a specific type.
/// Instances are generated by the source generator and accessed via
/// <see cref="PaktSerializerContext"/>.
/// </summary>
/// <typeparam name="T">The serializable type.</typeparam>
public sealed class PaktTypeInfo<T>
{
    /// <summary>
    /// Initializes a new <see cref="PaktTypeInfo{T}"/>.
    /// </summary>
    public PaktTypeInfo(
        PaktType paktType,
        IReadOnlyList<PaktPropertyInfo> properties)
    {
        PaktType = paktType;
        Properties = properties;
    }

    /// <summary>The PAKT type representation for <typeparamref name="T"/>.</summary>
    public PaktType PaktType { get; }

    /// <summary>Per-property metadata for serialization.</summary>
    public IReadOnlyList<PaktPropertyInfo> Properties { get; }

    // TODO: Add serialize/deserialize delegates when reader/writer are implemented.
    // public Func<ref PaktReader, T>? Deserialize { get; init; }
    // public Action<PaktWriter, T>? Serialize { get; init; }
}
