namespace Pakt.Serialization;

/// <summary>
/// Base class for source-generated serializer contexts.
/// Derive from this class and apply <see cref="PaktSerializableAttribute"/> to register types.
/// The source generator will produce a partial class with a <c>Default</c> singleton
/// and typed <see cref="PaktTypeInfo{T}"/> properties.
/// </summary>
public abstract class PaktSerializerContext
{
    /// <summary>
    /// Gets the serializer options associated with this context.
    /// </summary>
    public PaktSerializerOptions Options { get; }

    /// <summary>
    /// Initializes a new <see cref="PaktSerializerContext"/> with the specified options.
    /// </summary>
    protected PaktSerializerContext(PaktSerializerOptions? options = null)
    {
        Options = options ?? PaktSerializerOptions.Default;
    }

    /// <summary>
    /// Gets the <see cref="PaktTypeInfo{T}"/> for the specified type, or <c>null</c> if not registered.
    /// Override is generated by the source generator.
    /// </summary>
    public virtual PaktTypeInfo<T>? GetTypeInfo<T>() => null;
}
