namespace Pakt.Serialization;

/// <summary>
/// Provides metadata and serialization delegates for a specific type.
/// Instances are generated by the source generator and accessed via
/// <see cref="PaktSerializerContext"/>.
/// </summary>
/// <typeparam name="T">The serializable type.</typeparam>
public sealed class PaktTypeInfo<T>
{
    /// <summary>
    /// Delegate that deserializes a value of <typeparamref name="T"/> from a <see cref="PaktReader"/>.
    /// The reader should be positioned at the composite start token (e.g., StructStart).
    /// </summary>
    public delegate T DeserializeFunc(ref PaktReader reader);

    /// <summary>
    /// Delegate that serializes a value of <typeparamref name="T"/> to a <see cref="PaktWriter"/>.
    /// </summary>
    public delegate void SerializeAction(PaktWriter writer, T value);

    /// <summary>
    /// Initializes a new <see cref="PaktTypeInfo{T}"/>.
    /// </summary>
    public PaktTypeInfo(
        PaktType paktType,
        IReadOnlyList<PaktPropertyInfo> properties)
    {
        PaktType = paktType;
        Properties = properties;
    }

    /// <summary>The PAKT type representation for <typeparamref name="T"/>.</summary>
    public PaktType PaktType { get; }

    /// <summary>Per-property metadata for serialization.</summary>
    public IReadOnlyList<PaktPropertyInfo> Properties { get; }

    /// <summary>
    /// Source-generated delegate that deserializes a value from a <see cref="PaktReader"/>.
    /// </summary>
    public DeserializeFunc? Deserialize { get; init; }

    /// <summary>
    /// Source-generated delegate that serializes a value to a <see cref="PaktWriter"/>.
    /// </summary>
    public SerializeAction? Serialize { get; init; }
}
