namespace Pakt.Serialization;

/// <summary>
/// Non-generic metadata and read/write hooks for a serializable CLR type.
/// </summary>
public abstract class PaktTypeInfo
{
    /// <summary>
    /// Initializes a new <see cref="PaktTypeInfo"/>.
    /// </summary>
    protected PaktTypeInfo(
        Type clrType,
        PaktType paktType,
        IReadOnlyList<PaktPropertyInfo> properties)
    {
        ClrType = clrType;
        PaktType = paktType;
        Properties = properties;
    }

    /// <summary>The CLR type represented by this metadata.</summary>
    public Type ClrType { get; }

    /// <summary>The PAKT type representation for this CLR type.</summary>
    public PaktType PaktType { get; }

    /// <summary>Per-property metadata for serialization and materialization.</summary>
    public IReadOnlyList<PaktPropertyInfo> Properties { get; }

    /// <summary>
    /// Deserializes a value from the current reader position.
    /// </summary>
    internal abstract object? DeserializeObject(ref PaktReader reader, PaktConvertContext context);

    /// <summary>
    /// Serializes a CLR object using this type info.
    /// </summary>
    internal abstract void SerializeObject(PaktWriter writer, object? value);
}

/// <summary>
/// Provides metadata and serialization delegates for a specific CLR type.
/// Instances are generated by the source generator and accessed via
/// <see cref="PaktSerializerContext"/>.
/// </summary>
/// <typeparam name="T">The serializable type.</typeparam>
public sealed class PaktTypeInfo<T> : PaktTypeInfo
{
    /// <summary>
    /// Delegate that deserializes a value of <typeparamref name="T"/> from a <see cref="PaktReader"/>.
    /// The reader should be positioned at the start token for that value.
    /// </summary>
    public delegate T DeserializeFunc(ref PaktReader reader, PaktConvertContext context);

    /// <summary>
    /// Delegate that serializes a value of <typeparamref name="T"/> to a <see cref="PaktWriter"/>.
    /// </summary>
    public delegate void SerializeAction(PaktWriter writer, T value);

    /// <summary>
    /// Initializes a new <see cref="PaktTypeInfo{T}"/>.
    /// </summary>
    public PaktTypeInfo(
        PaktType paktType,
        IReadOnlyList<PaktPropertyInfo> properties)
        : base(typeof(T), paktType, properties)
    {
    }

    /// <summary>
    /// Source-generated delegate that deserializes a value from a <see cref="PaktReader"/>.
    /// </summary>
    public DeserializeFunc? Deserialize { get; init; }

    /// <summary>
    /// Source-generated delegate that serializes a value to a <see cref="PaktWriter"/>.
    /// </summary>
    public SerializeAction? Serialize { get; init; }

    internal override object? DeserializeObject(ref PaktReader reader, PaktConvertContext context)
    {
        if (Deserialize is null)
            throw new InvalidOperationException($"Type '{typeof(T).Name}' does not have a deserialize delegate.");

        return Deserialize(ref reader, context);
    }

    internal override void SerializeObject(PaktWriter writer, object? value)
    {
        if (Serialize is null)
            throw new InvalidOperationException($"Type '{typeof(T).Name}' does not have a serialize delegate.");

        Serialize(writer, (T)value!);
    }
}
