using System.Text;
using Pakt.Generators.Models;

namespace Pakt.Generators.Emitters;

/// <summary>
/// Emits the partial <c>PaktSerializerContext</c> subclass with
/// Default singleton, GetTypeInfo overrides, and deserialize method stubs.
/// </summary>
internal static class ContextEmitter
{
    public static string EmitContext(
        string contextClassName,
        string? contextNamespace,
        List<SerializableTypeModel> types)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (contextNamespace is not null)
        {
            sb.AppendLine($"namespace {contextNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {contextClassName}");
        sb.AppendLine("{");

        // Default singleton
        sb.AppendLine($"    private static {contextClassName}? _default;");
        sb.AppendLine($"    public static {contextClassName} Default => _default ??= new {contextClassName}();");
        sb.AppendLine();

        // Typed properties
        foreach (var type in types)
        {
            sb.AppendLine($"    private global::Pakt.PaktTypeInfo<{type.FullyQualifiedName}>? _{type.Name}TypeInfo;");
            sb.AppendLine($"    public global::Pakt.PaktTypeInfo<{type.FullyQualifiedName}> {type.Name} =>");
            sb.AppendLine($"        _{type.Name}TypeInfo ??= new global::Pakt.PaktTypeInfo<{type.FullyQualifiedName}>(\"{BuildPaktTypeName(type)}\")");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            Deserialize = static (ref global::Pakt.PaktSequenceReader reader) => Deserialize{type.Name}(ref reader),");
            sb.AppendLine($"        }};");
            sb.AppendLine();
        }

        // GetTypeInfo<T>
        sb.AppendLine("    public override global::Pakt.PaktTypeInfo<T>? GetTypeInfo<T>()");
        sb.AppendLine("    {");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return (global::Pakt.PaktTypeInfo<T>)(object){type.Name};");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetTypeInfo(Type)
        sb.AppendLine("    public override global::Pakt.PaktTypeInfo? GetTypeInfo(global::System.Type type)");
        sb.AppendLine("    {");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return {type.Name};");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Deserialize methods
        foreach (var type in types)
        {
            sb.Append(DeserializerEmitter.EmitDeserializeMethod(type));
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string BuildPaktTypeName(SerializableTypeModel model)
    {
        var sb = new StringBuilder();
        sb.Append('{');
        bool first = true;
        foreach (var prop in model.Properties)
        {
            if (prop.IsIgnored) continue;
            if (!first) sb.Append(' ');
            sb.Append(prop.PaktName);
            sb.Append(':');
            sb.Append(MapKindToPaktType(prop));
            first = false;
        }
        sb.Append('}');
        return sb.ToString();
    }

    private static string MapKindToPaktType(PropertyModel prop)
    {
        string baseType = prop.Kind switch
        {
            PaktTypeKind.String => "str",
            PaktTypeKind.Int => "int",
            PaktTypeKind.Long => "int",
            PaktTypeKind.Decimal => "dec",
            PaktTypeKind.Double => "float",
            PaktTypeKind.Float => "float",
            PaktTypeKind.Bool => "bool",
            PaktTypeKind.Guid => "uuid",
            PaktTypeKind.DateOnly => "date",
            PaktTypeKind.DateTimeOffset => "ts",
            PaktTypeKind.ByteArray => "bin",
            PaktTypeKind.List => $"[{MapElementKindToPaktType(prop.ElementTypeFqn)}]",
            PaktTypeKind.Map => $"<{MapElementKindToPaktType(prop.KeyTypeFqn)} => {MapElementKindToPaktType(prop.ValueTypeFqn)}>",
            PaktTypeKind.Struct => "struct",
            _ => "unknown",
        };

        return prop.IsNullable ? baseType + "?" : baseType;
    }

    private static string MapElementKindToPaktType(string? fqn)
    {
        if (fqn is null) return "unknown";
        if (fqn.Contains("String")) return "str";
        if (fqn.Contains("Int32")) return "int";
        if (fqn.Contains("Int64")) return "int";
        if (fqn.Contains("Boolean")) return "bool";
        if (fqn.Contains("Double")) return "float";
        if (fqn.Contains("Decimal")) return "dec";
        return "str";
    }
}
