using System.Text;

using Pakt.Generators.Models;

namespace Pakt.Generators.Emitters;

/// <summary>
/// Emits the partial <c>PaktSerializerContext</c> subclass with
/// Default singleton, GetTypeInfo overrides, property metadata, and deserialize methods.
/// </summary>
internal static class ContextEmitter
{
    public static string EmitContext(
        string contextClassName,
        string? contextNamespace,
        List<SerializableTypeModel> types)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (contextNamespace is not null)
        {
            sb.AppendLine($"namespace {contextNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {contextClassName}");
        sb.AppendLine("{");

        // Default singleton
        sb.AppendLine($"    private static {contextClassName}? _default;");
        sb.AppendLine($"    public static {contextClassName} Default => _default ??= new {contextClassName}();");
        sb.AppendLine();

        // Typed properties
        foreach (var type in types)
        {
            string typeFqn = type.FullyQualifiedName;
            string sig = BuildPaktTypeSignature(type);

            sb.AppendLine($"    private global::Pakt.PaktTypeInfo<{typeFqn}>? _{type.Name}TypeInfo;");
            sb.AppendLine($"    public global::Pakt.PaktTypeInfo<{typeFqn}> {type.Name} =>");
            sb.AppendLine($"        _{type.Name}TypeInfo ??= new global::Pakt.PaktTypeInfo<{typeFqn}>(\"{sig}\", {type.Name}Properties)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            Deserialize = static (ref global::Pakt.PaktReader reader) => DeserializeValue{type.Name}(ref reader),");
            sb.AppendLine($"            DeserializeUnit = static (ref global::Pakt.PaktReader reader, global::Pakt.PaktSerializationOptions options) => DeserializeUnit{type.Name}(ref reader, options),");
            sb.AppendLine($"        }};");
            sb.AppendLine();
        }

        // PaktPropertyInfo arrays
        foreach (var type in types)
        {
            EmitPropertyInfoArray(sb, type);
        }

        // GetTypeInfo<T>
        sb.AppendLine("    public override global::Pakt.PaktTypeInfo<T>? GetTypeInfo<T>()");
        sb.AppendLine("    {");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return (global::Pakt.PaktTypeInfo<T>)(object){type.Name};");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetTypeInfo(Type)
        sb.AppendLine("    public override global::Pakt.PaktTypeInfo? GetTypeInfo(global::System.Type type)");
        sb.AppendLine("    {");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return {type.Name};");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Deserialize methods
        foreach (var type in types)
        {
            sb.Append(DeserializerEmitter.EmitValueDeserializeMethod(type));
            sb.AppendLine();
            sb.Append(DeserializerEmitter.EmitUnitDeserializeMethod(type));
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitPropertyInfoArray(StringBuilder sb, SerializableTypeModel model)
    {
        sb.AppendLine($"    private static readonly global::Pakt.PaktPropertyInfo[] {model.Name}Properties =");
        sb.AppendLine("    [");

        int order = 0;
        foreach (var prop in model.Properties)
        {
            if (prop.IsIgnored) continue;
            bool isCollection = prop.Kind is PaktTypeKind.List or PaktTypeKind.Map;
            sb.AppendLine($"        new global::Pakt.PaktPropertyInfo");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            PaktName = \"{prop.PaktName}\",");
            sb.AppendLine($"            ClrName = \"{prop.ClrName}\",");
            sb.AppendLine($"            Order = {order},");
            sb.AppendLine($"            IsCollection = {(isCollection ? "true" : "false")},");
            sb.AppendLine($"        }},");
            order++;
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    internal static string BuildPaktTypeSignature(SerializableTypeModel model)
    {
        var sb = new StringBuilder();
        sb.Append('{');
        bool first = true;
        foreach (var prop in model.Properties)
        {
            if (prop.IsIgnored) continue;
            if (!first) sb.Append(' ');
            sb.Append(prop.PaktName);
            sb.Append(':');
            sb.Append(MapKindToPaktType(prop));
            first = false;
        }
        sb.Append('}');
        return sb.ToString();
    }

    internal static string MapKindToPaktType(PropertyModel prop)
    {
        string baseType = prop.Kind switch
        {
            PaktTypeKind.String => "str",
            PaktTypeKind.Int => "int",
            PaktTypeKind.Long => "int",
            PaktTypeKind.Decimal => "dec",
            PaktTypeKind.Double => "float",
            PaktTypeKind.Float => "float",
            PaktTypeKind.Bool => "bool",
            PaktTypeKind.Guid => "uuid",
            PaktTypeKind.DateOnly => "date",
            PaktTypeKind.DateTimeOffset => "ts",
            PaktTypeKind.ByteArray => "bin",
            PaktTypeKind.List => $"[{MapElementKindToPaktType(prop.ElementTypeFqn)}]",
            PaktTypeKind.Map => $"<{MapElementKindToPaktType(prop.KeyTypeFqn)} = {MapElementKindToPaktType(prop.ValueTypeFqn)}>",
            PaktTypeKind.Struct => "struct",
            _ => "unknown",
        };

        return prop.IsNullable ? baseType + "?" : baseType;
    }

    private static string MapElementKindToPaktType(string? fqn)
    {
        if (fqn is null) return "unknown";
        if (fqn.Contains("String")) return "str";
        if (fqn.Contains("Int32")) return "int";
        if (fqn.Contains("Int64")) return "int";
        if (fqn.Contains("Boolean")) return "bool";
        if (fqn.Contains("Double")) return "float";
        if (fqn.Contains("Decimal")) return "dec";
        return "str";
    }
}