using System.Text;

namespace Pakt.Cli.Codegen;

/// <summary>
/// Emits C# source from a <see cref="PaktTypeModel"/>.
/// </summary>
internal static class CSharpEmitter
{
    public static string Emit(PaktTypeModel model, string? ns, string? className)
    {
        string rootClass = className ?? ToPascal(Path.GetFileNameWithoutExtension(model.FileName)) + "Unit";
        string contextClass = ToPascal(Path.GetFileNameWithoutExtension(model.FileName)) + "Context";

        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {model.FileName}");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        // Emit enums
        foreach (var (_, enumInfo) in model.Enums.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.AppendLine($"public enum {enumInfo.CSharpName}");
            sb.AppendLine("{");
            foreach (string member in enumInfo.Members)
            {
                sb.AppendLine($"    {ToPascal(member)},");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Emit struct classes
        foreach (var (_, structInfo) in model.Structs.OrderBy(s => s.Key, StringComparer.Ordinal))
        {
            sb.AppendLine($"public class {structInfo.CSharpName}");
            sb.AppendLine("{");
            foreach (var field in structInfo.Fields)
            {
                string attrName = !string.Equals(field.PaktName, field.CSharpName, StringComparison.OrdinalIgnoreCase)
                    ? $"    [Pakt.PaktProperty(\"{field.PaktName}\")]\n" : "";
                string defaultVal = GetDefaultValue(field.Type);
                sb.Append(attrName);
                sb.AppendLine($"    public {field.Type.TypeName} {field.CSharpName} {{ get; set; }}{defaultVal}");
                sb.AppendLine();
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Emit root unit class
        sb.AppendLine($"public class {rootClass}");
        sb.AppendLine("{");
        foreach (var stmt in model.Statements)
        {
            sb.AppendLine($"    [Pakt.PaktProperty(\"{stmt.PaktName}\")]");
            string defaultVal = GetDefaultValue(stmt.Type);
            sb.AppendLine($"    public {stmt.Type.TypeName} {stmt.CSharpName} {{ get; set; }}{defaultVal}");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Emit serializer context
        var allTypes = new List<string> { rootClass };
        allTypes.AddRange(model.Structs.Values.Select(s => s.CSharpName));

        sb.AppendLine("// Serializer context — register with source generator");
        foreach (string typeName in allTypes)
        {
            string fullName = ns != null ? $"{ns}.{typeName}" : typeName;
            sb.AppendLine($"[Pakt.PaktSerializable(typeof({fullName}))]");
        }
        sb.AppendLine($"public partial class {contextClass} : Pakt.PaktSerializerContext;");

        return sb.ToString();
    }

    private static string GetDefaultValue(CSharpType type)
    {
        if (type.IsNullable) return "";
        if (string.Equals(type.TypeName, "string", StringComparison.Ordinal)) return " = \"\";";
        if (type.IsList) return " = [];";
        if (type.IsMap) return " = [];";
        if (string.Equals(type.TypeName, "byte[]", StringComparison.Ordinal)) return " = [];";
        if (type.IsStruct) return " = new();";
        return "";
    }

    private static string ToPascal(string s) => TypeExtractor.ToPascalCase(s);
}