using System.Collections.Generic;
using System.Linq;
using Pakt.Generators.Model;

namespace Pakt.Generators.Emitters
{
    internal static class PaktSourceEmitter
    {
        public static string Emit(
            string contextClassName,
            string contextNamespace,
            IReadOnlyList<SerializableTypeModel> types)
        {
            var sb = new SourceBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(contextNamespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {contextNamespace}");
                sb.OpenBrace();
            }

            EmitPartialContext(sb, contextClassName, types);

            if (hasNamespace)
            {
                sb.CloseBrace();
            }

            return sb.ToString();
        }

        private static void EmitPartialContext(
            SourceBuilder sb,
            string contextClassName,
            IReadOnlyList<SerializableTypeModel> types)
        {
            sb.AppendLine($"partial class {contextClassName}");
            sb.OpenBrace();

            // Default singleton
            sb.AppendLine($"private static {contextClassName}? _default;");
            sb.AppendLine($"public static {contextClassName} Default => _default ??= new {contextClassName}();");
            sb.AppendLine();

            // Type info properties + factory methods
            foreach (var type in types)
            {
                EmitTypeInfoProperty(sb, type, types);
            }

            // Deserialize methods
            foreach (var type in types)
            {
                EmitDeserializeMethod(sb, type, types);
            }

            // Serialize methods
            foreach (var type in types)
            {
                EmitSerializeMethod(sb, type, types);
            }

            // Skip helper
            EmitSkipHelper(sb);

            // GetTypeInfo<T> override
            EmitGetTypeInfo(sb, types);

            sb.CloseBrace();
        }

        private static void EmitGetTypeInfo(SourceBuilder sb, IReadOnlyList<SerializableTypeModel> types)
        {
            sb.AppendLine("public override global::Pakt.Serialization.PaktTypeInfo<T>? GetTypeInfo<T>()");
            sb.OpenBrace();
            foreach (var type in types)
            {
                sb.AppendLine($"if (typeof(T) == typeof({type.FullyQualifiedName})) return (global::Pakt.Serialization.PaktTypeInfo<T>)(object){type.Name};");
            }
            sb.AppendLine("return null;");
            sb.CloseBrace();
            sb.AppendLine();
        }

        private static void EmitTypeInfoProperty(SourceBuilder sb, SerializableTypeModel type, IReadOnlyList<SerializableTypeModel> allTypes)
        {
            var fqn = type.FullyQualifiedName;
            var name = type.Name;

            sb.AppendLine($"private global::Pakt.Serialization.PaktTypeInfo<{fqn}>? _{name};");
            sb.AppendLine($"public global::Pakt.Serialization.PaktTypeInfo<{fqn}> {name} => _{name} ??= Create{name}TypeInfo();");
            sb.AppendLine();

            sb.AppendLine($"private static global::Pakt.Serialization.PaktTypeInfo<{fqn}> Create{name}TypeInfo()");
            sb.OpenBrace();

            // Build PaktType
            var activeProps = type.Properties.Where(p => !p.IsIgnored).ToList();
            sb.AppendLine("return new global::Pakt.Serialization.PaktTypeInfo<" + fqn + ">(");
            sb.Indent();

            // PaktType.Struct(...)
            sb.AppendLine("global::Pakt.PaktType.Struct(global::System.Collections.Immutable.ImmutableArray.Create(");
            sb.Indent();
            for (int i = 0; i < activeProps.Count; i++)
            {
                var p = activeProps[i];
                var comma = i < activeProps.Count - 1 ? "," : "";
                sb.AppendLine($"new global::Pakt.PaktField(\"{p.PaktName}\", {EmitPaktTypeExpr(p, allTypes)}){comma}");
            }
            sb.Dedent();
            sb.AppendLine(")),");

            // PaktPropertyInfo array
            sb.AppendLine("new global::Pakt.Serialization.PaktPropertyInfo[]");
            sb.OpenBrace();
            for (int i = 0; i < activeProps.Count; i++)
            {
                var p = activeProps[i];
                var comma = i < activeProps.Count - 1 ? "," : "";
                sb.AppendLine($"new global::Pakt.Serialization.PaktPropertyInfo(\"{p.ClrName}\", \"{p.PaktName}\", {EmitPaktTypeExpr(p, allTypes)}, {p.Order}){comma}");
            }
            sb.CloseBrace();

            sb.Dedent();
            sb.AppendLine(")");
            sb.OpenBrace();
            sb.AppendLine($"Deserialize = Deserialize{name},");
            sb.AppendLine($"Serialize = Serialize{name},");
            sb.CloseBrace(";");
            sb.CloseBrace();
            sb.AppendLine();
        }

        private static void EmitDeserializeMethod(
            SourceBuilder sb,
            SerializableTypeModel type,
            IReadOnlyList<SerializableTypeModel> allTypes)
        {
            var fqn = type.FullyQualifiedName;
            var name = type.Name;
            var activeProps = type.Properties.Where(p => !p.IsIgnored).ToList();

            sb.AppendLine($"public static {fqn} Deserialize{name}(ref global::Pakt.PaktReader reader)");
            sb.OpenBrace();
            sb.AppendLine($"var result = new {fqn}();");

            sb.AppendLine("while (reader.Read())");
            sb.OpenBrace();
            sb.AppendLine("if (reader.TokenType == global::Pakt.PaktTokenType.StructEnd) break;");
            sb.AppendLine();

            sb.AppendLine("switch (reader.CurrentName)");
            sb.OpenBrace();

            foreach (var p in activeProps)
            {
                sb.AppendLine($"case \"{p.PaktName}\":");
                sb.Indent();
                EmitDeserializeProperty(sb, p, allTypes);
                sb.AppendLine("break;");
                sb.Dedent();
            }

            // Default: skip unknown
            sb.AppendLine("default:");
            sb.Indent();
            sb.AppendLine("SkipCurrentValue(ref reader);");
            sb.AppendLine("break;");
            sb.Dedent();

            sb.CloseBrace(); // switch
            sb.CloseBrace(); // while

            sb.AppendLine("return result;");
            sb.CloseBrace(); // method
            sb.AppendLine();
        }

        private static void EmitDeserializeProperty(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes)
        {
            if (prop.IsNullable)
            {
                sb.AppendLine("if (reader.TokenType == global::Pakt.PaktTokenType.Nil)");
                sb.OpenBrace();
                sb.AppendLine($"result.{prop.ClrName} = default;");
                sb.CloseBrace();
                sb.AppendLine("else");
                sb.OpenBrace();
                EmitDeserializeValue(sb, prop, allTypes, $"result.{prop.ClrName}");
                sb.CloseBrace();
            }
            else
            {
                EmitDeserializeValue(sb, prop, allTypes, $"result.{prop.ClrName}");
            }
        }

        private static void EmitDeserializeValue(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string target)
        {
            switch (prop.PaktKind)
            {
                case PaktTypeKind.Str:
                    sb.AppendLine($"{target} = reader.GetString();");
                    break;
                case PaktTypeKind.Int:
                    sb.AppendLine($"{target} = {EmitIntReadExpr(prop.TypeFullName)};");
                    break;
                case PaktTypeKind.Dec:
                    sb.AppendLine($"{target} = reader.GetDecimal();");
                    break;
                case PaktTypeKind.Float:
                    sb.AppendLine($"{target} = {EmitFloatReadExpr(prop.TypeFullName)};");
                    break;
                case PaktTypeKind.Bool:
                    sb.AppendLine($"{target} = reader.GetBoolean();");
                    break;
                case PaktTypeKind.Uuid:
                    sb.AppendLine($"{target} = reader.GetGuid();");
                    break;
                case PaktTypeKind.Date:
                    sb.AppendLine($"{target} = reader.GetDate();");
                    break;
                case PaktTypeKind.Ts:
                    sb.AppendLine($"{target} = reader.GetTimestamp();");
                    break;
                case PaktTypeKind.Bin:
                    sb.AppendLine("var _binData = new byte[reader.ValueSpan.Length / 2];");
                    sb.AppendLine("reader.GetBytesFromBin(_binData);");
                    sb.AppendLine($"{target} = _binData;");
                    break;
                case PaktTypeKind.Atom:
                    sb.AppendLine($"{target} = reader.GetAtom();");
                    break;
                case PaktTypeKind.Struct:
                    EmitDeserializeNested(sb, prop, allTypes, target);
                    break;
                case PaktTypeKind.List:
                    EmitDeserializeList(sb, prop, allTypes, target);
                    break;
                case PaktTypeKind.Map:
                    EmitDeserializeMap(sb, prop, allTypes, target);
                    break;
            }
        }

        private static void EmitDeserializeNested(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string target)
        {
            var nestedType = allTypes.FirstOrDefault(t =>
                t.FullyQualifiedName == prop.NestedTypeFullName);

            if (nestedType is not null)
            {
                sb.AppendLine($"{target} = Deserialize{nestedType.Name}(ref reader);");
            }
            else
            {
                sb.AppendLine("SkipCurrentValue(ref reader);");
            }
        }

        private static void EmitDeserializeList(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string target)
        {
            var elemFqn = prop.ElementTypeFullName ?? "object";
            var elemKind = prop.ElementPaktKind ?? PaktTypeKind.Str;

            sb.AppendLine($"var _list_{prop.ClrName} = new global::System.Collections.Generic.List<{elemFqn}>();");
            sb.AppendLine("while (reader.Read())");
            sb.OpenBrace();
            sb.AppendLine("if (reader.TokenType == global::Pakt.PaktTokenType.ListEnd) break;");

            if (elemKind == PaktTypeKind.Struct)
            {
                var nestedType = allTypes.FirstOrDefault(t =>
                    t.FullyQualifiedName == prop.NestedTypeFullName);
                if (nestedType is not null)
                {
                    sb.AppendLine($"_list_{prop.ClrName}.Add(Deserialize{nestedType.Name}(ref reader));");
                }
                else
                {
                    sb.AppendLine("SkipCurrentValue(ref reader);");
                }
            }
            else
            {
                sb.AppendLine($"_list_{prop.ClrName}.Add({EmitScalarRead(elemKind, elemFqn)});");
            }

            sb.CloseBrace(); // while

            if (prop.IsArray)
            {
                sb.AppendLine($"{target} = _list_{prop.ClrName}.ToArray();");
            }
            else
            {
                sb.AppendLine($"{target} = _list_{prop.ClrName};");
            }
        }

        private static void EmitDeserializeMap(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string target)
        {
            var keyFqn = prop.KeyTypeFullName ?? "string";
            var keyKind = prop.KeyPaktKind ?? PaktTypeKind.Str;
            var valFqn = prop.ValueTypeFullName ?? "object";
            var valKind = prop.ValuePaktKind ?? PaktTypeKind.Str;

            sb.AppendLine($"var _dict_{prop.ClrName} = new global::System.Collections.Generic.Dictionary<{keyFqn}, {valFqn}>();");
            sb.AppendLine("while (reader.Read())");
            sb.OpenBrace();
            sb.AppendLine("if (reader.TokenType == global::Pakt.PaktTokenType.MapEnd) break;");
            sb.AppendLine($"var _key_{prop.ClrName} = {EmitScalarRead(keyKind, keyFqn)};");
            sb.AppendLine("reader.Read();");

            if (valKind == PaktTypeKind.Struct)
            {
                var nestedType = allTypes.FirstOrDefault(t =>
                    t.FullyQualifiedName == prop.NestedTypeFullName);
                if (nestedType is not null)
                {
                    sb.AppendLine($"_dict_{prop.ClrName}[_key_{prop.ClrName}] = Deserialize{nestedType.Name}(ref reader);");
                }
                else
                {
                    sb.AppendLine("SkipCurrentValue(ref reader);");
                }
            }
            else
            {
                sb.AppendLine($"_dict_{prop.ClrName}[_key_{prop.ClrName}] = {EmitScalarRead(valKind, valFqn)};");
            }

            sb.CloseBrace(); // while
            sb.AppendLine($"{target} = _dict_{prop.ClrName};");
        }

        private static void EmitSerializeMethod(
            SourceBuilder sb,
            SerializableTypeModel type,
            IReadOnlyList<SerializableTypeModel> allTypes)
        {
            var fqn = type.FullyQualifiedName;
            var name = type.Name;
            var activeProps = type.Properties.Where(p => !p.IsIgnored).ToList();

            sb.AppendLine($"public static void Serialize{name}(global::Pakt.PaktWriter writer, {fqn} value)");
            sb.OpenBrace();
            sb.AppendLine("writer.WriteStructStart();");

            foreach (var p in activeProps)
            {
                EmitSerializeProperty(sb, p, allTypes);
            }

            sb.AppendLine("writer.WriteStructEnd();");
            sb.CloseBrace(); // method
            sb.AppendLine();
        }

        private static void EmitSerializeProperty(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes)
        {
            if (prop.IsNullable)
            {
                sb.AppendLine($"if (value.{prop.ClrName} is null)");
                sb.OpenBrace();
                sb.AppendLine("writer.WriteNilValue();");
                sb.CloseBrace();
                sb.AppendLine("else");
                sb.OpenBrace();
                // For nullable value types, unwrap with .Value
                var expr = IsValueTypeKind(prop.PaktKind)
                    ? $"value.{prop.ClrName}.Value"
                    : $"value.{prop.ClrName}";
                EmitSerializeValue(sb, prop, allTypes, expr);
                sb.CloseBrace();
            }
            else
            {
                EmitSerializeValue(sb, prop, allTypes, $"value.{prop.ClrName}");
            }
        }

        private static bool IsValueTypeKind(PaktTypeKind kind)
        {
            switch (kind)
            {
                case PaktTypeKind.Int:
                case PaktTypeKind.Dec:
                case PaktTypeKind.Float:
                case PaktTypeKind.Bool:
                case PaktTypeKind.Uuid:
                case PaktTypeKind.Date:
                case PaktTypeKind.Ts:
                    return true;
                default:
                    return false;
            }
        }

        private static void EmitSerializeValue(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string expr)
        {
            switch (prop.PaktKind)
            {
                case PaktTypeKind.Str:
                    sb.AppendLine($"writer.WriteStringValue({expr}.AsSpan());");
                    break;
                case PaktTypeKind.Int:
                    sb.AppendLine($"writer.WriteIntValue({expr});");
                    break;
                case PaktTypeKind.Dec:
                    sb.AppendLine($"writer.WriteDecimalValue({expr});");
                    break;
                case PaktTypeKind.Float:
                    sb.AppendLine($"writer.WriteFloatValue({expr});");
                    break;
                case PaktTypeKind.Bool:
                    sb.AppendLine($"writer.WriteBoolValue({expr});");
                    break;
                case PaktTypeKind.Uuid:
                    sb.AppendLine($"writer.WriteUuidValue({expr});");
                    break;
                case PaktTypeKind.Date:
                    sb.AppendLine($"writer.WriteDateValue({expr});");
                    break;
                case PaktTypeKind.Ts:
                    sb.AppendLine($"writer.WriteTimestampValue({expr});");
                    break;
                case PaktTypeKind.Bin:
                    sb.AppendLine($"writer.WriteBinValue({expr});");
                    break;
                case PaktTypeKind.Atom:
                    sb.AppendLine($"writer.WriteAtomValue({expr}.AsSpan());");
                    break;
                case PaktTypeKind.Struct:
                    EmitSerializeNested(sb, prop, allTypes, expr);
                    break;
                case PaktTypeKind.List:
                    EmitSerializeList(sb, prop, allTypes, expr);
                    break;
                case PaktTypeKind.Map:
                    EmitSerializeMap(sb, prop, allTypes, expr);
                    break;
            }
        }

        private static void EmitSerializeNested(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string expr)
        {
            var nestedType = allTypes.FirstOrDefault(t =>
                t.FullyQualifiedName == prop.NestedTypeFullName);

            if (nestedType is not null)
            {
                sb.AppendLine($"Serialize{nestedType.Name}(writer, {expr});");
            }
        }

        private static void EmitSerializeList(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string expr)
        {
            var elemKind = prop.ElementPaktKind ?? PaktTypeKind.Str;

            sb.AppendLine("writer.WriteListStart();");
            sb.AppendLine($"foreach (var _item in {expr})");
            sb.OpenBrace();

            if (elemKind == PaktTypeKind.Struct)
            {
                var nestedType = allTypes.FirstOrDefault(t =>
                    t.FullyQualifiedName == prop.NestedTypeFullName);
                if (nestedType is not null)
                {
                    sb.AppendLine($"Serialize{nestedType.Name}(writer, _item);");
                }
            }
            else
            {
                sb.AppendLine(EmitScalarWrite(elemKind, "_item"));
            }

            sb.CloseBrace();
            sb.AppendLine("writer.WriteListEnd();");
        }

        private static void EmitSerializeMap(
            SourceBuilder sb,
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string expr)
        {
            var keyKind = prop.KeyPaktKind ?? PaktTypeKind.Str;
            var valKind = prop.ValuePaktKind ?? PaktTypeKind.Str;

            sb.AppendLine("writer.WriteMapStart();");
            sb.AppendLine($"foreach (var _entry in {expr})");
            sb.OpenBrace();

            sb.AppendLine(EmitScalarWrite(keyKind, "_entry.Key"));
            sb.AppendLine("writer.WriteMapKeySeparator();");

            if (valKind == PaktTypeKind.Struct)
            {
                var nestedType = allTypes.FirstOrDefault(t =>
                    t.FullyQualifiedName == prop.NestedTypeFullName);
                if (nestedType is not null)
                {
                    sb.AppendLine($"Serialize{nestedType.Name}(writer, _entry.Value);");
                }
            }
            else
            {
                sb.AppendLine(EmitScalarWrite(valKind, "_entry.Value"));
            }

            sb.CloseBrace();
            sb.AppendLine("writer.WriteMapEnd();");
        }

        private static void EmitSkipHelper(SourceBuilder sb)
        {
            sb.AppendLine("private static void SkipCurrentValue(ref global::Pakt.PaktReader reader)");
            sb.OpenBrace();
            sb.AppendLine("switch (reader.TokenType)");
            sb.OpenBrace();
            sb.AppendLine("case global::Pakt.PaktTokenType.ScalarValue:");
            sb.AppendLine("case global::Pakt.PaktTokenType.Nil:");
            sb.Indent();
            sb.AppendLine("return;");
            sb.Dedent();
            sb.AppendLine("case global::Pakt.PaktTokenType.StructStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.ListStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.MapStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.TupleStart:");
            sb.Indent();
            sb.AppendLine("int depth = 1;");
            sb.AppendLine("while (depth > 0 && reader.Read())");
            sb.OpenBrace();
            sb.AppendLine("switch (reader.TokenType)");
            sb.OpenBrace();
            sb.AppendLine("case global::Pakt.PaktTokenType.StructStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.ListStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.MapStart:");
            sb.AppendLine("case global::Pakt.PaktTokenType.TupleStart:");
            sb.Indent();
            sb.AppendLine("depth++;");
            sb.AppendLine("break;");
            sb.Dedent();
            sb.AppendLine("case global::Pakt.PaktTokenType.StructEnd:");
            sb.AppendLine("case global::Pakt.PaktTokenType.ListEnd:");
            sb.AppendLine("case global::Pakt.PaktTokenType.MapEnd:");
            sb.AppendLine("case global::Pakt.PaktTokenType.TupleEnd:");
            sb.Indent();
            sb.AppendLine("depth--;");
            sb.AppendLine("break;");
            sb.Dedent();
            sb.CloseBrace(); // inner switch
            sb.CloseBrace(); // while
            sb.AppendLine("return;");
            sb.Dedent();
            sb.CloseBrace(); // outer switch
            sb.CloseBrace(); // method
        }

        // --- Helpers for PaktType expression generation ---

        private static string EmitPaktTypeExpr(PropertyModel prop, IReadOnlyList<SerializableTypeModel> allTypes)
        {
            var nullable = prop.IsNullable ? ", nullable: true" : "";

            switch (prop.PaktKind)
            {
                case PaktTypeKind.Str: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Str{nullable})";
                case PaktTypeKind.Int: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Int{nullable})";
                case PaktTypeKind.Dec: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Dec{nullable})";
                case PaktTypeKind.Float: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Float{nullable})";
                case PaktTypeKind.Bool: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Bool{nullable})";
                case PaktTypeKind.Uuid: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Uuid{nullable})";
                case PaktTypeKind.Date: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Date{nullable})";
                case PaktTypeKind.Ts: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Ts{nullable})";
                case PaktTypeKind.Bin: return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Bin{nullable})";

                case PaktTypeKind.Atom:
                    var members = string.Join(", ", prop.AtomMembers.Select(m => $"\"{m}\""));
                    return $"global::Pakt.PaktType.AtomSet(global::System.Collections.Immutable.ImmutableArray.Create({members}){nullable})";

                case PaktTypeKind.List:
                    var elemKind = prop.ElementPaktKind ?? PaktTypeKind.Str;
                    var elemExpr = elemKind == PaktTypeKind.Struct
                        ? EmitNestedStructTypeExpr(prop, allTypes, string.Empty)
                        : EmitScalarPaktTypeExpr(elemKind);
                    return $"global::Pakt.PaktType.List({elemExpr}{nullable})";

                case PaktTypeKind.Map:
                    var keyKind = prop.KeyPaktKind ?? PaktTypeKind.Str;
                    var valKind = prop.ValuePaktKind ?? PaktTypeKind.Str;
                    var keyExpr = EmitScalarPaktTypeExpr(keyKind);
                    var valExpr = valKind == PaktTypeKind.Struct
                        ? EmitNestedStructTypeExpr(prop, allTypes, string.Empty)
                        : EmitScalarPaktTypeExpr(valKind);
                    return $"global::Pakt.PaktType.Map({keyExpr}, {valExpr}{nullable})";

                case PaktTypeKind.Struct:
                    return EmitNestedStructTypeExpr(prop, allTypes, nullable);

                default:
                    return $"global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Str{nullable})";
            }
        }

        private static string EmitNestedStructTypeExpr(
            PropertyModel prop,
            IReadOnlyList<SerializableTypeModel> allTypes,
            string nullable)
        {
            var nestedType = allTypes.FirstOrDefault(t =>
                t.FullyQualifiedName == prop.NestedTypeFullName);

            if (nestedType is null)
                return $"global::Pakt.PaktType.Struct(global::System.Collections.Immutable.ImmutableArray<global::Pakt.PaktField>.Empty{nullable})";

            var nestedProps = nestedType.Properties.Where(p => !p.IsIgnored).ToList();
            if (nestedProps.Count == 0)
                return $"global::Pakt.PaktType.Struct(global::System.Collections.Immutable.ImmutableArray<global::Pakt.PaktField>.Empty{nullable})";

            var fields = string.Join(", ",
                nestedProps.Select(p =>
                    $"new global::Pakt.PaktField(\"{p.PaktName}\", {EmitPaktTypeExpr(p, allTypes)})"));

            return $"global::Pakt.PaktType.Struct(global::System.Collections.Immutable.ImmutableArray.Create({fields}){nullable})";
        }

        private static string EmitScalarPaktTypeExpr(PaktTypeKind kind)
        {
            switch (kind)
            {
                case PaktTypeKind.Str: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Str)";
                case PaktTypeKind.Int: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Int)";
                case PaktTypeKind.Dec: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Dec)";
                case PaktTypeKind.Float: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Float)";
                case PaktTypeKind.Bool: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Bool)";
                case PaktTypeKind.Uuid: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Uuid)";
                case PaktTypeKind.Date: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Date)";
                case PaktTypeKind.Ts: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Ts)";
                case PaktTypeKind.Bin: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Bin)";
                default: return "global::Pakt.PaktType.Scalar(global::Pakt.PaktScalarType.Str)";
            }
        }

        // --- Helpers for read/write expressions ---

        /// <summary>Returns a complete int-read expression with checked casts as needed.</summary>
        private static string EmitIntReadExpr(string typeFullName)
        {
            if (typeFullName.EndsWith("Int64") || typeFullName == "long")
                return "reader.GetInt64()";
            if (typeFullName.EndsWith("UInt64") || typeFullName == "ulong")
                return "(ulong)reader.GetInt64()";
            if (typeFullName.EndsWith("Int32") || typeFullName == "int")
                return "checked((int)reader.GetInt64())";
            if (typeFullName.EndsWith("Int16") || typeFullName == "short")
                return "checked((short)reader.GetInt64())";
            if (typeFullName.EndsWith("Byte") && !typeFullName.EndsWith("SByte"))
                return "checked((byte)reader.GetInt64())";
            if (typeFullName.EndsWith("SByte") || typeFullName == "sbyte")
                return "checked((sbyte)reader.GetInt64())";
            if (typeFullName.EndsWith("UInt32") || typeFullName == "uint")
                return "checked((uint)reader.GetInt64())";
            if (typeFullName.EndsWith("UInt16") || typeFullName == "ushort")
                return "checked((ushort)reader.GetInt64())";
            return "checked((int)reader.GetInt64())";
        }

        /// <summary>Returns a complete float-read expression with cast as needed.</summary>
        private static string EmitFloatReadExpr(string typeFullName)
        {
            if (typeFullName.EndsWith("Single") || typeFullName == "float")
                return "(float)reader.GetDouble()";
            return "reader.GetDouble()";
        }

        private static string EmitScalarRead(PaktTypeKind kind, string typeFullName)
        {
            switch (kind)
            {
                case PaktTypeKind.Str: return "reader.GetString()";
                case PaktTypeKind.Int: return EmitIntReadExpr(typeFullName);
                case PaktTypeKind.Dec: return "reader.GetDecimal()";
                case PaktTypeKind.Float: return EmitFloatReadExpr(typeFullName);
                case PaktTypeKind.Bool: return "reader.GetBoolean()";
                case PaktTypeKind.Uuid: return "reader.GetGuid()";
                case PaktTypeKind.Date: return "reader.GetDate()";
                case PaktTypeKind.Ts: return "reader.GetTimestamp()";
                case PaktTypeKind.Atom: return "reader.GetAtom()";
                default: return "reader.GetString()";
            }
        }

        private static string EmitScalarWrite(PaktTypeKind kind, string expr)
        {
            switch (kind)
            {
                case PaktTypeKind.Str: return $"writer.WriteStringValue({expr}.AsSpan());";
                case PaktTypeKind.Int: return $"writer.WriteIntValue({expr});";
                case PaktTypeKind.Dec: return $"writer.WriteDecimalValue({expr});";
                case PaktTypeKind.Float: return $"writer.WriteFloatValue({expr});";
                case PaktTypeKind.Bool: return $"writer.WriteBoolValue({expr});";
                case PaktTypeKind.Uuid: return $"writer.WriteUuidValue({expr});";
                case PaktTypeKind.Date: return $"writer.WriteDateValue({expr});";
                case PaktTypeKind.Ts: return $"writer.WriteTimestampValue({expr});";
                case PaktTypeKind.Bin: return $"writer.WriteBinValue({expr});";
                case PaktTypeKind.Atom: return $"writer.WriteAtomValue({expr}.AsSpan());";
                default: return $"writer.WriteStringValue({expr}.AsSpan());";
            }
        }
    }
}
