using System.Runtime.InteropServices;

namespace Pakt;

/// <summary>
/// Metadata for a single property in a PAKT-serializable type.
/// Used by <see cref="PaktSerializer"/> for statement-to-property binding
/// and policy enforcement. Generated by the source generator.
/// </summary>
[StructLayout(LayoutKind.Auto)]
public readonly struct PaktPropertyInfo
{
    /// <summary>The PAKT statement name (may differ from CLR name via [PaktProperty]).</summary>
    public required string PaktName { get; init; }

    /// <summary>The CLR property name.</summary>
    public required string ClrName { get; init; }

    /// <summary>Positional order within the type.</summary>
    public required int Order { get; init; }

    /// <summary>Whether this property is required (missing = error).</summary>
    public bool IsRequired { get; init; }

    /// <summary>Whether this property is a collection type (list/map → eligible for pack).</summary>
    public bool IsCollection { get; init; }

    /// <summary>Optional converter type override from [PaktConverter] attribute.</summary>
    public Type? ConverterType { get; init; }
}