using System.Buffers;

namespace Pakt;

/// <summary>
/// Non-generic base for type info — allows collection and lookup by <see cref="Type"/>.
/// </summary>
public abstract class PaktTypeInfo
{
    /// <summary>The CLR type this info describes.</summary>
    public abstract Type ClrType { get; }

    /// <summary>The PAKT type signature (e.g. <c>{name:str version:int}</c>).</summary>
    public abstract string PaktTypeName { get; }
}

/// <summary>
/// Deserialize delegate signature for source-generated deserializers.
/// </summary>
public delegate T PaktDeserializeFunc<out T>(ref PaktSequenceReader reader);

/// <summary>
/// Type metadata and deserialize delegate for <typeparamref name="T"/>.
/// Instances are generated by the source generator.
/// </summary>
public sealed class PaktTypeInfo<T> : PaktTypeInfo
{
    private readonly string _paktTypeName;

    public PaktTypeInfo(string paktTypeName) => _paktTypeName = paktTypeName;

    /// <summary>Delegate that deserializes <typeparamref name="T"/> from a reader.</summary>
    public required PaktDeserializeFunc<T> Deserialize { get; init; }

    /// <inheritdoc />
    public override Type ClrType => typeof(T);

    /// <inheritdoc />
    public override string PaktTypeName => _paktTypeName;
}