using System.Buffers;

namespace Pakt;

/// <summary>
/// Non-generic base for type info — allows collection and lookup by <see cref="Type"/>.
/// </summary>
public abstract class PaktTypeInfo
{
    /// <summary>The CLR type this info describes.</summary>
    public abstract Type ClrType { get; }

    /// <summary>The PAKT type signature (e.g. <c>{name:str version:int}</c>).</summary>
    public abstract string PaktTypeSignature { get; }

    /// <summary>
    /// Property metadata for statement-to-property binding in the unit materializer.
    /// Empty for types that don't participate in unit-level deserialization (e.g. nested structs).
    /// </summary>
    public abstract ReadOnlySpan<PaktPropertyInfo> Properties { get; }
}

/// <summary>
/// Deserialize delegate signature for source-generated deserializers.
/// Operates on <see cref="PaktValidatingReader"/> for type-enforced reading.
/// </summary>
public delegate T PaktDeserializeFunc<out T>(ref PaktValidatingReader reader);

/// <summary>
/// Unit-level deserialize delegate using the raw sequence reader.
/// Generated per-type: zero-alloc statement matching, no annotation parsing.
/// </summary>
public delegate T PaktRawUnitDeserializeFunc<out T>(
    ref PaktSequenceReader reader,
    PaktSerializationOptions options);

/// <summary>
/// Unit-level deserialize delegate that handles statement matching and policies.
/// Generated per-type: reads statements by name, applies policies, returns T.
/// </summary>
public delegate T PaktUnitDeserializeFunc<out T>(
    ref PaktValidatingReader reader,
    PaktSerializationOptions options);

/// <summary>
/// Type metadata and deserialize delegates for <typeparamref name="T"/>.
/// Instances are generated by the source generator.
/// </summary>
public sealed class PaktTypeInfo<T> : PaktTypeInfo
{
    private readonly string _paktTypeSignature;
    private readonly PaktPropertyInfo[] _properties;

    public PaktTypeInfo(string paktTypeSignature, PaktPropertyInfo[]? properties = null)
    {
        _paktTypeSignature = paktTypeSignature;
        _properties = properties ?? [];
    }

    /// <summary>
    /// Delegate that deserializes a single struct value of <typeparamref name="T"/>
    /// from a positional token stream (used inside composites and by converters).
    /// </summary>
    public required PaktDeserializeFunc<T> Deserialize { get; init; }

    /// <summary>
    /// Delegate that deserializes <typeparamref name="T"/> from a full PAKT unit
    /// using the raw sequence reader. Preferred path — no annotation parsing overhead.
    /// </summary>
    public PaktRawUnitDeserializeFunc<T>? RawDeserializeUnit { get; init; }

    /// <summary>
    /// Delegate that deserializes <typeparamref name="T"/> from a full PAKT unit,
    /// handling statement name matching and policies.
    /// Null for types that are never deserialized at the unit level.
    /// </summary>
    public PaktUnitDeserializeFunc<T>? DeserializeUnit { get; init; }

    /// <inheritdoc />
    public override Type ClrType => typeof(T);

    /// <inheritdoc />
    public override string PaktTypeSignature => _paktTypeSignature;

    /// <inheritdoc />
    public override ReadOnlySpan<PaktPropertyInfo> Properties => _properties;
}